---
language: java
script: ./gradlew clean :yafot:shadowJar

os:
    - linux

jdk:
    - oraclejdk8

sudo: false
deploy:
  provider: releases
  api_key: "${TRAVIS_TOKEN}"
  file: "yafot/build/libs/jObbifier-all.jar"
  skip_cleanup: true
  on:
    tags: true

notifications:
    email:
        - root@cybikbase.com
