---
language: java
script: ./gradlew clean :yafot:shadowJar

os:
    - linux

jdk:
    - oraclejdk8

sudo: false
deploy:
    provider: releases
    api_key: "${TRAVIS_TOKEN}"
    file:
        - yafot/build/libs/yafot-all.jar
        - googlejobb/build/libs/googlejobb.jar
    skip_cleanup: true
    on:
        repo: cybik/yafot
        tags: true

notifications:
    email:
        - root@cybikbase.com
